application: ree-melbourne
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: latest

handlers:
- url: /test
  script: test.app
- url: /.*
  script: ree_melbourne.app

builtins:
- remote_api: on